services:
  deepseek-ocr:
    image: vllm/vllm-openai:v0.7.3
    container_name: deepseek-ocr
    runtime: nvidia
    ports:
      - "8089:8000"
    volumes:
      - /home/aigc/.cache/huggingface:/root/.cache/huggingface
    entrypoint: bash -c "python3 -m vllm.entrypoints.openai.api_server --model deepseek-ai/DeepSeek-OCR --max-model-len 4096"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
